org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=hytale.doryanbessiere.villager
plugin_name=HytaleVillager
plugin_description=A villager plugin
plugin_author=Doryan BESSIERE
plugin_website=hytale.doryanbessiere.fr
plugin_main_entrypoint=hytale.doryanbessiere.fr.villager.HytaleVillager
server_version=*
